export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#3a4a49',
        'on-secondary-fixed': '#400009',
        'on-surface-variant': '#514345',
        'primary-fixed-dim': '#fbb3c1',
        'surface-dim': '#c9dcf3',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#6b3743',
        'on-primary-container': '#7b4551',
        'background': '#f7f9ff',
        'inverse-on-surface': '#e8f2ff',
        'secondary': '#ba002c',
        'primary-container': '#ffb7c5',
        'on-tertiary-container': '#485858',
        'primary-fixed': '#ffd9df',
        'surface': '#f7f9ff',
        'secondary-fixed': '#ffdad9',
        'surface-container': '#e3efff',
        'outline': '#837375',
        'tertiary-fixed-dim': '#b8cac9',
        'surface-container-low': '#edf4ff',
        'surface-variant': '#d1e4fb',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bccecd',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'inverse-surface': '#203243',
        'on-primary': '#ffffff',
        'on-surface': '#091d2e',
        'on-secondary-fixed-variant': '#920021',
        'surface-bright': '#f7f9ff',
        'tertiary': '#516161',
        'tertiary-fixed': '#d4e6e5',
        'on-primary-fixed': '#360c19',
        'on-secondary-container': '#fffbff',
        'inverse-primary': '#fbb3c1',
        'primary': '#864e5a',
        'secondary-container': '#df2842',
        'secondary-fixed-dim': '#ffb3b3',
        'surface-container-highest': '#d1e4fb',
        'surface-container-high': '#d9eaff',
        'on-tertiary-fixed': '#0e1e1e',
        'error': '#ba1a1a',
        'surface-tint': '#864e5a',
        'outline-variant': '#d6c2c4',
        'on-background': '#091d2e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        sm: '0.25rem',
        md: '0.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-margin': '20px',
        gutter: '16px',
        'card-gap': '12px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'display-jp': ['Noto Sans JP'],
        'headline-lg': ['Montserrat'],
        'headline-lg-mobile': ['Montserrat'],
        'kanji-card': ['Noto Sans JP'],
        'label-caps': ['Inter'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-jp': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'kanji-card': ['64px', { lineHeight: '1.1', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
}
